name: CI-CD Pipeline to AWS

on:
  push:
    branches:
      - 'master'
      - 'feature/*'


jobs:
  buildAndPushToRegistry:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: 'linux/arm64,linux/amd64,linux/riscv64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6'

      - name: Log in to the Container registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/glef1x/glqiwiapi-proxy:latest

  pushDeploymentPackage:
    if: "success()"
    needs: buildAndPushToRegistry
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@master
        with:
          lfs: 'true'

      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x '*.git*'

      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "Referrer proxy"
          environment_name: Referrerproxy-env
          version_label: "Referrerproxy-${{ steps.format-time.outputs.replaced }}"
          region: ${{ secrets.AWS_REGION }}
          deployment_package: ./referrer/proxy/deploy.zip
